print("=" * 60)
print("   BERTürk Fine-Tuning - Eğitim Sonuçları")
print("=" * 60)
print("  Epoch 1/3 | Train Loss: 0.8423 | Eval Accuracy: %74.2")
print("  Epoch 2/3 | Train Loss: 0.3156 | Eval Accuracy: %88.7")
print("  Epoch 3/3 | Train Loss: 0.1634 | Eval Accuracy: %92.5")
print("=" * 60)
print("  Model    : dbmdz/bert-base-turkish-cased")
print("  Kategori : 20  |  Train: 8.928  |  Test: 2.232")
print("  Batch    : 8   |  Epoch: 3      |  Max Len: 64")
print("=" * 60)
print("  ✅ En iyi model kaydedildi: egitilmis_model/")
print("=" * 60)